QUEUE_CONFIG_PATH = 'custom_queues_config.yml'

QUEUE_INSERT_EVENT = 'INSERT_%d'
QUEUE_EXIT_EVENT = 'EXIT_%d'
QUEUE_MOVE_EVENT = 'MOVE_FROM_%d_TO_%d'

QUEUE_EVENT_SEPARATOR = '_'

GLIB_LINEAR_A = 1103515245
GLIB_LINEAR_M = 2**31
GLIB_LINEAR_C = 12345